### ISSUE TITLE
CELERY_QUEUES is not defined

### ISSUE THREAD

**Issue by worsco** [subuk/awx-rpm#5]
Attempting to install 1.0.1.223.
- Built RPMs from awx-1.0.1.223.tar.gz
- Installed Tower via:
  yum install ./awx-1.0.1.223-1.el7.centos.x86_64.rpm
- Installed rabbitmq (per directions)
- Installed postgresql 9.6 (per directions)
- executed "ssudo -u awx /opt/awx/bin/awx-manage migrate" results in:
Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 93, in manage
    prepare_env()
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 48, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/settings/production.py", line 95, in <module>
    include(settings_file, optional(settings_files), scope=locals())
  File "/opt/awx/embedded/lib/python2.7/site-packages/split_settings/tools.py", line 101, in include
    exec(compile(to_compile.read(), included_file, 'exec'), scope)
  File "/etc/awx/settings.py", line 34, in <module>
    CELERY_QUEUES += (Queue(CLUSTER_HOST_ID, Exchange(CLUSTER_HOST_ID), routing_key=CLUSTER_HOST_ID),)
NameError: name 'CELERY_QUEUES' is not defined

Also, executing "sudo -u awx /opt/awx/bin/awx-manage --help" results in:
Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 93, in manage
    prepare_env()
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 48, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/settings/production.py", line 95, in <module>
    include(settings_file, optional(settings_files), scope=locals())
  File "/opt/awx/embedded/lib/python2.7/site-packages/split_settings/tools.py", line 101, in include
    exec(compile(to_compile.read(), included_file, 'exec'), scope)
  File "/etc/awx/settings.py", line 34, in <module>
    CELERY_QUEUES += (Queue(CLUSTER_HOST_ID, Exchange(CLUSTER_HOST_ID), routing_key=CLUSTER_HOST_ID),)
NameError: name 'CELERY_QUEUES' is not defined

**Comment by worsco** [comment]
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

**Comment by subuk** [comment]
Looks like configuration variables have been renamed. You need to rename CELERY_QUEUES to CELERY_TASK_QUEUES and CELERY_ROUTES to CELERY_TASK_ROUTES in /etc/awx/settings.py. https://github.com/ansible/awx/blob/devel/installer/image_build/files/settings.py#L34-L36

I will fix configuration file example shipped with this RPM soon.

**Comment by subuk** [comment]
Fixed here https://github.com/subuk/awx-rpm/commit/e870e25841a384fbfd9866ff0104713df3ac15aa

**Comment by ajihandoko** [comment]
After I change from CELERY_QUEUES to CELERY_TASK_QUEUES the following error appears : 
`raise ImproperlyConfigured(error_msg)`
`django.core.exceptions.ImproperlyConfigured: 'transaction_hooks.backends.postgresql_psycopg2' isn't an available database backend.`
`Try using 'django.db.backends.XXX', where XXX is one of:`
    `'mysql', 'oracle', 'postgresql', 'sqlite3'`
`Error was: No module named transaction_hooks.backends.postgresql_psycopg2.base`

**Comment by subuk** [comment]
Yes, database engine has been changed too, please, check patch above

**Comment by worsco** [comment]
Patches work for me.  Successfully installed awx-1.0.1.225-1.el7.centos.x86_64 as an RPM and the site is functional.
